micronaut:
  server:
    port: 8000
  application:
    name: microHomework

datasources:
  default:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://my-postgresql.default.svc.cluster.local:5432/usersdb
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
#    schema-generate: CREATE # Автоматическое создание схемы на основании сущностей
#    schema-generate-create-schemas: true # Указывает, что нужно создавать схемы, если они не существуют

flyway:
  enabled: true
  locations: classpath:db/migration
  datasources:
    default:
      schemas: micro
      enabled: true
  #  locations: classpath:db/migration

jpa:
  default:
    entity-scan:
      packages: 'leo.landau'
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: none
          #тут очень странная тема, так как локально flyway отрабатывает, и создает схему micro, а вот в k8s - нет,
          #поэтому поставила сюда костыль в виде просьбы хиберу самому создавать схемы, если что-то не так идет
#          create_namespaces: true

logger:
  level:
    root: INFO
    io:
      micronaut:
        sql: DEBUG
    org:
      flywaydb: DEBUG

management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        exclude: '*'
