micronaut:
  server:
    port: 8000
  application:
    name: microHomework
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  security:
    authentication: bearer

datasources:
  default:
    url: jdbc:postgresql://my-postgresql.default.svc.cluster.local:5432/usersdb
    username: postgres
    password: cG9zdGdyZXM=
#    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES

flyway:
  enabled: true
  locations: classpath:db/migration
  datasources:
    default:
      schemas: micro
      enabled: true

jpa:
  default:
    entity-scan:
      packages: 'leo.landau'
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: none
          #тут очень странная тема, так как локально flyway отрабатывает, и создает схему micro, а вот в k8s - нет,
          #поэтому поставила сюда костыль в виде просьбы хиберу самому создавать схемы, если что-то не так идет
          #т.e. эта опция включается только в configmap
#          create_namespaces: true

logger:
  level:
    root: INFO
    io:
      micronaut:
        sql: DEBUG
    org:
      flywaydb: DEBUG

#IMPORTANT NOTE: Once set up, the Prometheus-compatible metrics can be scraped from the path /prometheus
endpoints:
  prometheus:
    sensitive: false #делаем метрики свободными для просмотра всем
