@startuml
actor Client
control "Auth Service" as AuthService
control "Location Service" as LocationService
control "Pets Service" as PetsService
control "Notification Service" as NotificationService

Client -> AuthService : Authenticate User
AuthService -> Client : Return Token

Client -> LocationService : Get Current Location (with Token)
LocationService -> Client : Return Location

Client -> PetsService : Get Lost Pets List (with Token, Location)
PetsService -> Client : Return Lost Pets List

Client -> PetsService : Get Pet Details (with Token, Pet ID)
PetsService -> Client : Return Pet Details

Client -> PetsService : Pet Found (with Token, Pet ID, Photo)
PetsService -> Client : Waiting for Confirmation Pet Found

PetsService -> NotificationService : Send Found Notification (Pet ID)
NotificationService -> Owner : Notify Owner (Pet Found)
Owner -> PetsService : Confirm Pet Found
PetsService -> NotificationService : Send Confirmation Pet Found Notification (Pet ID)
NotificationService -> Client : Notify Client Confirmation Pet Found (Pet ID)
@enduml
